  version: '3.8'

  services:
    nginx:
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      container_name: nginx
      ports:
        - "443:443"
      environment:
        - DOMAIN_NAME=${DOMAIN_NAME}
      volumes:
        - wordpress_data:/var/www/html
      restart: always
      networks:
        - inception_net
    mariadb:
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      container_name: mariadb
      env_file:
        - .env
      environment:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        WP_DB_NAME: ${WP_DB_NAME}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      volumes:
        - mariadb_data:/var/lib/mysql
        - ./requirements/mariadb/conf/my.cnf:/etc/my.cnf
      networks:
        - inception_net
      restart: always
    wordpress:
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      container_name: wordpress
      restart: always
      depends_on:
        - mariadb
      environment:
        DOMAIN_NAME: ${DOMAIN_NAME}
        WP_TABLE_PREFIX: ${WP_TABLE_PREFIX}
        WP_DB_NAME: ${WP_DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
        WP_EDITOR_USER: ${WP_EDITOR_USER}
        WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD}
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - inception_net
    ftp_server:
      build:
        context: ./bonus/ftp
        args:
          FTP_USER: ${FTP_USER}
          FTP_PASSWORD: ${FTP_PASSWORD}
      container_name: ftp_server
      restart: always
      environment:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
      ports:
        - "21:21"
        - "21000:21000"
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - inception_net

  volumes:
    wordpress_data:
    mariadb_data:

  networks:
    inception_net:
      driver: bridge