  version: '3.8'

  services:
    nginx:
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      container_name: nginx
      ports:
        - "443:443"
        # - "80:80"
      volumes:
        - wordpress_data:/var/www/html/wordpress
        - adminer_data:/var/www/html/adminer
      restart: on-failure
      networks:
        - inception_net

    mariadb:
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      container_name: mariadb
      env_file:
        - .env
      environment:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        WP_DB_NAME: ${WP_DB_NAME}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      volumes:
        - mariadb_data:/var/lib/mysql
        - ./requirements/mariadb/conf/my.cnf:/etc/my.cnf
      restart: on-failure
      networks:
        - inception_net

    wordpress:
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      container_name: wordpress
      depends_on:
        - mariadb
      environment:
        WP_TABLE_PREFIX: ${WP_TABLE_PREFIX}
        WP_DB_NAME: ${WP_DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
        WP_EDITOR_USER: ${WP_EDITOR_USER}
        WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD}
      volumes:
        - wordpress_data:/var/www/html/wordpress
      restart: on-failure
      networks:
        - inception_net

    adminer:
      build:
        context: ./bonus/adminer
        dockerfile: Dockerfile
      container_name: adminer
      depends_on:
        - mariadb
      volumes:
        - adminer_data:/var/www/html/adminer
      restart: on-failure
      networks:
        - inception_net

    portfolio:
      build:
        context: ./bonus/portfolio
        dockerfile: Dockerfile
      container_name: portfolio
      volumes:
        - portfolio_data:/var/www/html/portfolio
      restart: on-failure
      networks:
        - inception_net

    ftp_server:
      build:
        context: ./bonus/ftp
        dockerfile: Dockerfile
        args:
          FTP_USER: ${FTP_USER}
          FTP_PASSWORD: ${FTP_PASSWORD}
      container_name: ftp_server
      depends_on:
        - wordpress
      environment:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
      ports:
        - "21:21"
        - "21000:21000"
      volumes:
        - wordpress_data:/var/www/html
      restart: on-failure
      networks:
        - inception_net

    cadvisor:
     build:
        context: ./bonus/cadvisor
        dockerfile: Dockerfile
     container_name: cadvisor
     volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - cadvisor_data:/usr/local/bin
     restart: on-failure
     networks:
     - inception_net

  volumes:
    wordpress_data:
      driver: local
      driver_opts:
        type: none
        device: /home/thmouty/data/html/wordpress
        o: bind
    mariadb_data:
      driver: local
      driver_opts:
        type: none
        device: /home/thmouty/data/mariadb
        o: bind
    adminer_data:
      driver: local
      driver_opts:
        type: none
        device: /home/thmouty/data/html/adminer
        o: bind
    portfolio_data:
      driver: local
      driver_opts:
        type: none
        device: /home/thmouty/data/html/portfolio
        o: bind
    cadvisor_data:
        driver: local
        driver_opts:
            type: none
            device: /home/thmouty/data/cadvisor
            o: bind

  networks:
    inception_net:
      driver: bridge