version: '3.8'

services:
  # nginx:
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #   environment:
  #     - DOMAIN_NAME=${DOMAIN_NAME}
  #   restart: always
  #   networks:
  #     - inception_net
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - inception_net
    restart: always

networks:
  inception_net:
    driver: bridge